#!/usr/bin/env python3
"""Turn the measurement campaign into the project's findings.

Loads every run into DuckDB, answers the three questions the project set out to
test, runs the miner and the regression gate, and writes docs/FINDINGS.md.

Nothing here decides what counts as a result. A finding that does not reproduce
is written down as a null, because the alternative is a report that can only
ever agree with its author.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "python"))

import pandas as pd  # noqa: E402

from switchback.db import load as dbload  # noqa: E402
from switchback.db import queries as Q  # noqa: E402
from switchback.mine import gate as gatemod  # noqa: E402
from switchback.mine import subgroups  # noqa: E402

SEED = 20260917


def fmt_ci(point: float, lo: float, hi: float, scale: float = 100.0, unit: str = "%") -> str:
    return f"{point * scale:.2f}{unit} [{lo * scale:.2f}, {hi * scale:.2f}]"


def section(out: list[str], title: str) -> None:
    out.append("")
    out.append(f"## {title}")
    out.append("")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--results", default="data/results")
    ap.add_argument("--db", default="data/results/switchback.duckdb")
    ap.add_argument("--out", default="docs/FINDINGS.md")
    ap.add_argument("--dataset", default="av2_val")
    ap.add_argument("--n-boot", type=int, default=10000)
    ap.add_argument("--reload", action="store_true")
    args = ap.parse_args()

    db_path = Path(args.db)
    if args.reload and db_path.exists():
        db_path.unlink()
    con = dbload.open_db(db_path)

    # sb_batch writes one metrics CSV per run and one features CSV per dataset,
    # so the files are loaded by glob rather than by the fixed names
    # load_run_dir expects. Runs first: the loader's orphan check needs the run
    # row to exist before its metrics arrive.
    results = Path(args.results)
    counts: dict[str, int] = {}
    runs_csv = results / "runs.csv"
    if not runs_csv.exists():
        print(f"no runs.csv in {results}; nothing to analyse")
        return 1
    counts["runs"] = dbload.load_runs_csv(con, runs_csv)
    # A CSV that is still being written has its header sitting in the writer's
    # stdio buffer, so it reads as headerless. Report and skip rather than
    # aborting the whole analysis, which matters when inspecting a campaign
    # that is still in flight.
    for loader, pattern in ((dbload.load_features_csv, "features_*.csv"),
                            (dbload.load_metrics_csv, "metrics_*.csv")):
        for f in sorted(results.glob(pattern)):
            try:
                counts[f.name] = loader(con, f)
            except Exception as exc:  # noqa: BLE001
                print(f"  skipped {f.name}: {exc}")
    print("loaded:", json.dumps(counts, indent=2)[:600])

    runs = con.execute(
        "SELECT run_id, config_name, agent_mode, planner, n_scenarios, hardware "
        "FROM runs ORDER BY run_id"
    ).df()
    have = set(runs["run_id"])
    print(f"runs present: {sorted(have)}")

    out: list[str] = []
    out.append("# Findings")
    out.append("")
    out.append(
        "Generated by `scripts/analyze.py`. Read `docs/LIMITATIONS.md` first: every "
        "number below is a property of this benchmark and this planner, not of driving."
    )
    out.append("")
    out.append("## Provenance")
    out.append("")
    out.append("| run | config | agents | planner | scenarios |")
    out.append("| --- | --- | --- | --- | --- |")
    for _, r in runs.iterrows():
        out.append(
            f"| `{r.run_id}` | {r.config_name} | {r.agent_mode} | {r.planner} | {r.n_scenarios:,} |"
        )
    hw = sorted(set(runs["hardware"].dropna()))
    out.append("")
    out.append("Hardware, verbatim from the runs table: " + "; ".join(f"`{h}`" for h in hw))
    splits = dbload.split_counts(con)
    out.append("")
    out.append(
        f"Discovery/confirmation split: {splits.get('discovery', 0):,} / "
        f"{splits.get('confirmation', 0):,}, assigned once from a hash of the scenario id."
    )

    # ---- Finding (a): does log-replay flatter the planner? --------------------
    section(out, "Finding (a): how much log-replay evaluation flatters the planner")
    if {"baseline_log_replay", "baseline_reactive"} <= have:
        out.append(
            "Same planner, same configuration, same scenarios, two agent models. Paired "
            "over scenario id, bootstrapped over **scenarios** rather than timesteps, "
            "because 109 steps of one scenario are not 109 independent draws."
        )
        out.append("")
        out.append("| metric | log-replay | reactive | absolute change | ratio |")
        out.append("| --- | --- | --- | --- | --- |")
        summaries = {}
        for metric in [
            "at_fault_collision",
            "collision",
            "drivable_area_violation",
            "comfort_violation",
        ]:
            try:
                c = Q.log_replay_vs_reactive(
                    con,
                    metric=metric,
                    config_name="baseline",
                    dataset=args.dataset,
                    planner="ilqr",
                    n_boot=args.n_boot,
                    seed=SEED,
                )
            except Exception as exc:  # noqa: BLE001
                out.append(f"| {metric} | not computed: {exc} | | | |")
                continue
            summaries[metric] = c
            out.append(
                f"| `{metric}` | {c.log_replay * 100:.2f}% | {c.reactive * 100:.2f}% | "
                f"{fmt_ci(c.delta, c.delta_lo, c.delta_hi)} pts | "
                f"{c.ratio:.2f}x [{c.ratio_lo:.2f}, {c.ratio_hi:.2f}] |"
            )
        out.append("")
        out.append(f"Paired scenarios: {getattr(summaries.get('at_fault_collision'), 'n_paired', 0):,}.")
        a = summaries.get("at_fault_collision")
        if a is not None:
            if a.delta_lo > 0:
                out.append(
                    f"\n**Log-replay understates the at-fault collision rate by "
                    f"{a.ratio:.2f}x** (95% CI [{a.ratio_lo:.2f}, {a.ratio_hi:.2f}]). The "
                    "interval excludes 1.0, so the effect is not attributable to sampling."
                )
            elif a.delta_hi < 0:
                out.append(
                    f"\n**Log-replay overstates the at-fault collision rate by "
                    f"{1 / a.ratio:.2f}x.** This is the opposite of the hypothesis and is "
                    "reported as measured."
                )
            else:
                out.append(
                    f"\n**Null result on at-fault collisions.** The ratio is {a.ratio:.2f}x with "
                    f"a 95% interval of [{a.ratio_lo:.2f}, {a.ratio_hi:.2f}], which contains 1.0. "
                    "This measurement does not establish that log-replay flatters the planner on "
                    "the metric that actually scores the planner. Reported rather than discarded."
                )
            tot = summaries.get("collision")
            if tot is not None and tot.delta_hi < 0:
                out.append(
                    f"\n**But it does distort the headline collision rate, in the opposite "
                    f"direction to the usual assumption.** Total collisions run "
                    f"{1 / tot.ratio:.2f}x *higher* under log-replay "
                    f"(95% CI [{1 / tot.ratio_hi:.2f}, {1 / tot.ratio_lo:.2f}]). The mechanism is "
                    "visible in the split below: log-replay agents ignore the ego, so they drive "
                    "into it, and every one of those is a collision the planner did not cause."
                )
                nf = con.execute(
                    """
                    SELECT r.agent_mode,
                           avg(m.collision - m.at_fault_collision) * 100 AS not_at_fault_pct
                    FROM metrics m JOIN runs r USING (run_id)
                    WHERE r.config_name = 'baseline' AND m.status = 'ok'
                    GROUP BY 1 ORDER BY 1
                    """
                ).df()
                out.append("")
                out.append("| agent model | not-at-fault collision rate |")
                out.append("| --- | --- |")
                for _, row in nf.iterrows():
                    out.append(f"| {row.agent_mode} | {row.not_at_fault_pct:.2f}% |")
                out.append("")
                out.append(
                    "So the honest statement is not that log-replay flatters a planner. It is "
                    "that log-replay **manufactures collisions the planner is not responsible "
                    "for**, and a harness that reports a bare collision rate under log-replay "
                    "is measuring its own agent model as much as the policy."
                )
    else:
        out.append("_Not yet measured: both baseline runs are required._")

    # ---- The human floor -----------------------------------------------------
    section(out, "Every configuration side by side, against the human floor")
    if "human_log_replay" in have:
        hb = con.execute(
            """
            SELECT r.config_name, r.agent_mode,
                   avg(m.collision)                AS collision,
                   avg(m.at_fault_collision)       AS at_fault,
                   avg(m.drivable_area_violation)  AS offroad,
                   avg(m.wrong_direction)          AS wrong_dir,
                   count(*)                        AS n
            FROM metrics m JOIN runs r USING (run_id)
            WHERE m.status = 'ok'
            GROUP BY 1, 2 ORDER BY 1, 2
            """
        ).df()
        out.append(
            "The `human` row is the logged human's own trajectory through the identical "
            "metric suite. It is the floor: it says how much of every rate above belongs to "
            "the footprint constants, the map polygons and the metric definitions rather "
            "than to the planner. The `pure_pursuit` row is the other bound, a controller "
            "that tracks the route geometrically with no obstacle reasoning at all."
        )
        out.append("")
        out.append("| config | agents | collision | at-fault | off-road | wrong-way | n |")
        out.append("| --- | --- | --- | --- | --- | --- | --- |")
        for _, r in hb.iterrows():
            out.append(
                f"| {r.config_name} | {r.agent_mode} | {r.collision * 100:.2f}% | "
                f"{r.at_fault * 100:.2f}% | "
                f"{'n/a' if pd.isna(r.offroad) else f'{r.offroad * 100:.2f}%'} | "
                f"{r.wrong_dir * 100:.2f}% | {int(r.n):,} |"
            )
    else:
        out.append("_Not yet measured._")

    # ---- Finding (b): do the metrics disagree? -------------------------------
    section(out, "Finding (b): do the metrics rank configurations differently?")
    try:
        d = Q.metric_disagreement(con, agent_mode="reactive", dataset=args.dataset)
        out.append(
            "Configurations ranked by ADE-to-human against the mean rank over the safety "
            "and comfort suite. ADE is a **similarity** metric; if the two orderings "
            "disagree, optimising for human-likeness is measurably not the same as "
            "optimising for safety."
        )
        out.append("")
        out.append(d.table.to_markdown(index=False))
        out.append("")
        out.append(
            f"Kendall tau between the two rankings: **{d.kendall_tau:.3f}** (p = {d.kendall_p:.3f}, "
            f"{d.n_configs} configurations). "
            + (
                "The orderings disagree."
                if d.winners_disagree
                else "The orderings pick the same winner, so this finding does not reproduce here."
            )
        )
        out.append("")
        out.append(
            "With this few configurations the p-value is weak, and it is printed so that "
            "weakness is visible rather than implied. What is not weak is the mechanism, "
            "which the table shows directly: the configuration with the **best** ADE is "
            "`pure_pursuit`, the controller with no obstacle reasoning at all, and it "
            "collides in over half of its scenarios. It scores well on ADE precisely "
            "*because* it does not react. The logged human never had to avoid anything, so "
            "the closest trajectory to theirs is the one that also does not avoid anything. "
            "Ranking planners by human-likeness does not merely differ from ranking them by "
            "safety here, it inverts it."
        )
    except Exception as exc:  # noqa: BLE001
        out.append(f"_Not computed: {exc}_")

    # ---- Finding (c): is the long tail concentrated? -------------------------
    section(out, "Finding (c): is the failure mass concentrated or diffuse?")
    mine_run = "baseline_reactive" if "baseline_reactive" in have else None
    mined = {}
    if mine_run:
        feats = con.execute("SELECT * FROM features").df()
        mets = con.execute("SELECT * FROM metrics WHERE run_id = ?", [mine_run]).df()
        for target in ["at_fault_collision", "drivable_area_violation", "comfort_violation"]:
            if target not in mets.columns or mets[target].dropna().nunique() < 2:
                continue
            try:
                res = subgroups.mine(
                    feats, mets, target, seed=SEED, n_boot=args.n_boot, job_id=f"mine_{target}"
                )
            except Exception as exc:  # noqa: BLE001
                out.append(f"**{target}**: not mined: {exc}")
                continue
            mined[target] = res
            # Persist so the HTML report, which reads the database rather than
            # this script's memory, can render the classes and their renders.
            subgroups.write_results(con, res)
            sig = res.significant_classes
            share, n_union = res.union_mass_share(3)
            out.append(f"### `{target}`")
            out.append("")
            out.append(
                f"Confirmation-split base rate {res.conf_base_rate * 100:.2f}% "
                f"({res.conf_total_failures} failures in {res.n_confirmation:,} scenarios). "
                f"**{res.n_candidates_tested:,} candidate conjunctions tested**, "
                f"Benjamini-Hochberg at alpha = {res.alpha}. "
                f"{len(sig)} survive both the correction and a confirmation-split lift "
                f"interval excluding 1.0."
            )
            out.append("")
            out.append(
                f"Testing {res.n_candidates_tested:,} conjunctions at a raw "
                f"{res.alpha} threshold would be expected to throw up about "
                f"{res.expected_false_positives:.0f} significant-looking classes by chance "
                f"alone. That is what the correction is for, and it is why the candidate "
                f"count is printed next to the result rather than buried: a 3x lift found "
                f"among {res.n_candidates_tested:,} candidates is a different claim from one "
                f"found among five."
            )
            out.append("")
            if sig:
                out.append(
                    "| rule | conf. rate | lift | 95% CI | failure mass | q |"
                )
                out.append("| --- | --- | --- | --- | --- | --- |")
                for c in sig[:8]:
                    out.append(
                        f"| `{c.text}` | {c.conf_rate * 100:.1f}% | {c.conf_lift:.2f}x | "
                        f"[{c.conf_lift_lo:.2f}, {c.conf_lift_hi:.2f}] | "
                        f"{c.failure_mass_share * 100:.1f}% | {c.q_value:.3g} |"
                    )
                out.append("")
                out.append(
                    f"The top 3 classes by WRAcc together cover **{share * 100:.1f}%** of all "
                    f"confirmation-split failures ({n_union} of {res.conf_total_failures}). "
                    "The union, not the sum: the classes overlap by design, so adding their "
                    "individual mass shares would double count every scenario they share."
                )
            else:
                out.append(
                    "**No failure class survives correction.** With "
                    f"{res.n_candidates_tested:,} conjunctions tested, the best raw p-value "
                    "does not clear the Benjamini-Hochberg threshold. For this target the "
                    "failure mass is diffuse rather than concentrated, and that is the "
                    "honest version of this finding."
                )
            out.append("")
    else:
        out.append("_Not yet measured._")

    # ---- The regression gate -------------------------------------------------
    section(out, "The regression gate")
    sweeps = [r for r in have if r.startswith("sweep_")]
    if mine_run and sweeps:
        base_df = con.execute("SELECT * FROM metrics WHERE run_id = ?", [mine_run]).df()
        feats = con.execute("SELECT * FROM features").df()
        scopes = None
        if "at_fault_collision" in mined:
            scopes = gatemod.scopes_from_rules(
                feats, mined["at_fault_collision"].significant_classes[:4]
            )
        out.append(
            "Baseline against each one-weight change, paired over scenario id, bootstrapped "
            "over scenarios, Benjamini-Hochberg across the (scope, metric) family. "
            "**An interval containing zero is reported as inconclusive, never as a "
            "regression and never as an improvement.**"
        )
        out.append("")
        out.append("| candidate | regressions | improvements | inconclusive | verdict |")
        out.append("| --- | --- | --- | --- | --- |")
        for s in sorted(sweeps):
            cand_df = con.execute("SELECT * FROM metrics WHERE run_id = ?", [s]).df()
            try:
                g = gatemod.gate(
                    gatemod.RunMetrics(mine_run, base_df),
                    gatemod.RunMetrics(s, cand_df),
                    scopes=scopes,
                    n_boot=min(args.n_boot, 4000),
                    seed=SEED,
                    gate_id=f"gate_{s}",
                )
            except Exception as exc:  # noqa: BLE001
                out.append(f"| `{s}` | error: {exc} | | | |")
                continue
            gatemod.write_results(con, g)
            out.append(
                f"| `{s}` | {len(g.regressions)} | {len(g.improvements)} | "
                f"{len(g.inconclusive)} | {'PASS' if g.passed else 'FAIL'} |"
            )
        out.append("")
        out.append(
            "A gate whose cells are mostly inconclusive is a gate that is telling the truth "
            "about its power, not one that is broken."
        )
    else:
        out.append("_Not yet measured: needs the baseline and at least one sweep run._")

    # ---- Latency -------------------------------------------------------------
    section(out, "Planning latency")
    try:
        lat = Q.latency_aggregates(con, run_id="baseline_reactive")
        out.append(
            f"Over {lat.n_scenarios:,} scenarios and {lat.n_cycles:,} planning cycles, "
            f"the median scenario's p50 cycle time is **{lat.median_scenario_p50_us / 1000:.2f} ms** "
            f"and its p99 is **{lat.median_scenario_p99_us / 1000:.2f} ms**. "
            f"Cycle-weighted mean {lat.cycle_weighted_mean_us / 1000:.2f} ms, "
            f"worst single cycle {lat.max_us / 1000:.1f} ms. "
            f"The 10 Hz budget is 100 ms."
        )
        out.append("")
        out.append(
            "Heap allocations inside the planning cycle are not counted in a batch run: "
            "the counting `operator new` is linked only into `sb_bench` and the test "
            "binary, so a zero here would mean 'not measured' rather than 'measured and "
            "zero'. The measured figure is in the benchmark section and is asserted by "
            "`tests/test_no_alloc.cpp`, which also verifies that the counter itself works."
        )
        out.append("")
        out.append(lat.caveat)
    except Exception as exc:  # noqa: BLE001
        out.append(f"_Not computed: {exc}_")

    out.append("")
    out.append("---")
    out.append("")
    out.append(
        "Regenerate with `python scripts/analyze.py --reload`. The seed is fixed at "
        f"{SEED}, so every interval here is reproducible."
    )

    Path(args.out).write_text("\n".join(out) + "\n")
    print(f"wrote {args.out} ({len(out)} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
